name: Deploy Gallery

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Point stylesheet to CDN
        run: sed -i "s#\.\./kappaduck\.min\.css#https://cdn.jsdelivr.net/gh/kappaduck/brand@${{ github.ref_name }}/kappaduck.min.css#" src/index.html

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy src --project-name gallery --branch ${{ github.ref_name }}
